### ISSUE TITLE
無法訓練

### ISSUE THREAD

**Issue by Swdtl** [pionxzh/AI-PikaBall#2]
啟動遊戲之後，開始訓練時一直在Currently not in game...please wait..
![image11](https://github.com/pionxzh/AI-PikaBall/assets/149661102/3ab0d235-4e7a-4c3c-9315-056240416cf7)
不知道為什麼沒辦法訓練

**Comment by pionxzh** [comment]
我不碰這個很久了，你要自己debug了 🙏
