### ISSUE TITLE
我可以在我的項目中使用你的程式碼嗎？

### ISSUE THREAD

**Issue by Chaoray** [pionxzh/AI-PikaBall#4]
因為您似乎沒有授權文件，我想要使用的部分是 [memory.py](https://github.com/pionxzh/AI-PikaBall/blob/master/plugins/SerpentPikaBallGameAgentPlugin/files/helpers/memory.py)

**Comment by pionxzh** [comment]
可以

**Comment by Chaoray** [comment]
謝謝
